defaults:
    - base
    - _self_

actor:
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathEnvironment
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - int
test_dataset_names:
  - aime_2025